---
name: compose-os

on:
  push:
    branches:
      - main
    paths-ignore:
      - LICENSE
      - '**.md'
      - '**.txt'
  # schedule:
  #   - cron: 30 0,6,12,18 * * *
  workflow_dispatch: {}

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  registry: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ "fedora-minimal", "fedora-silverblue" ]

    container:
      # image: quay.io/fedora/fedora-coreos:stable
      image: quay.io/fedora/fedora-minimal:39
      options: '--user root --privileged -v /var/tmp:/var/tmp -v /tmp:/tmp'

    steps:
      - name: Install dependencies
        # run: rpm-ostree install --disablerepo='*' --enablerepo='fedora' --enablerepo='updates' distribution-gpg-keys
        run: dnf5 install -y distribution-gpg-keys git-core just podman rpm-ostree selinux-policy-targeted tar

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to registry
        run: podman login --username ${{ github.actor }} --password ${{ github.token }} ${{ env.registry }}

      # - name: Force initialize
      #   run: echo "force_initialize=1" >> $GITHUB_ENV
      #   if: github.event_name == 'workflow_dispatch'

      - name: Build ostree container
        run: rpm-ostree compose image --format=registry --initialize-mode if-not-exists ${{ matrix.os }}.yaml ${{ env.registry }}/${{ github.repository_owner }}/${{ matrix.os }}
